"""Tests for the brand icon assets and markup (#586).

The app shipped no favicon at all: no `rel="icon"` link, no `/favicon.ico`
route, no assets.  Browsers requested `/favicon.ico`, hit the catch-all 404,
and fell back to a generic glyph.

The spec is `docs/brand-icon.md`; the masters in `assets/brand/` are the source
of truth and everything under `static/` is generated by
`scripts/generate-icons.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from PIL import Image
from starlette.testclient import TestClient

_PROJECT_ROOT = Path(__file__).parent.parent
_STATIC = _PROJECT_ROOT / "src" / "worship_catalog" / "web" / "static"
_MASTERS = _PROJECT_ROOT / "assets" / "brand"
_BASE_TEMPLATE = _PROJECT_ROOT / "src" / "worship_catalog" / "web" / "templates" / "base.html"

_THEME_COLOR = "#1a1a2e"


class TestMastersAreCommitted:
    """The SVGs are the source the assets are reproducible from."""

    @pytest.mark.parametrize("name", ["icon.svg", "icon-16.svg", "icon-maskable.svg"])
    def test_master_exists(self, name: str) -> None:
        assert (_MASTERS / name).exists(), (
            f"{name} is missing — assets must be regenerable from committed masters"
        )

    def test_sixteen_px_master_is_hinted_not_a_copy(self) -> None:
        """The whole point of a second master is a fatter stem for the pixel grid."""
        standard = (_MASTERS / "icon.svg").read_text()
        hinted = (_MASTERS / "icon-16.svg").read_text()
        assert standard != hinted, (
            "icon-16.svg must be redrawn for the 16px grid, not a copy of icon.svg — "
            "otherwise the note's stem greys out below two device pixels"
        )
        assert 'width="4.4"' in hinted and 'width="3.2"' in standard, (
            "the hinted master should carry the fatter stem from docs/brand-icon.md"
        )

    def test_maskable_tile_is_square(self) -> None:
        """Platforms apply their own mask; a pre-rounded tile double-rounds."""
        maskable = (_MASTERS / "icon-maskable.svg").read_text()
        assert 'rx="14"' not in maskable.split("<rect")[1].split("/>")[0], (
            "the maskable tile must be square — the platform rounds it"
        )


class TestFaviconIco:
    """The .ico is the served icon, and it must really be multi-frame."""

    def test_ico_exists(self) -> None:
        assert (_STATIC / "favicon.ico").exists()

    def test_ico_has_all_three_frames(self) -> None:
        """Pillow silently writes a single-frame .ico if saved from the wrong image.

        `.save()` must be called on the LARGEST frame with the rest passed via
        `append_images`; saving from the 16px render succeeds and produces one
        frame. Asserting the count is the only way to catch that (docs/brand-icon.md).
        """
        with Image.open(_STATIC / "favicon.ico") as ico:
            sizes = {size for size in ico.info.get("sizes", set())}
        assert sizes == {(16, 16), (32, 32), (48, 48)}, (
            f"expected 16/32/48 frames, got {sorted(sizes)} — a single-frame .ico "
            "means the Pillow append_images trap bit again"
        )


class TestGeneratedPngs:
    @pytest.mark.parametrize(
        ("name", "expected"),
        [
            ("icon-192.png", 192),
            ("icon-512.png", 512),
            ("icon-maskable-512.png", 512),
            ("apple-touch-icon.png", 180),
        ],
    )
    def test_png_exists_at_the_right_size(self, name: str, expected: int) -> None:
        path = _STATIC / name
        assert path.exists(), f"{name} missing — run scripts/generate-icons.py"
        with Image.open(path) as img:
            assert img.size == (expected, expected), f"{name} is {img.size}"

    def test_apple_touch_icon_is_opaque(self) -> None:
        """iOS composites transparency onto black, which would ruin the navy tile."""
        with Image.open(_STATIC / "apple-touch-icon.png") as img:
            alpha = img.convert("RGBA").getchannel("A")
            assert alpha.getextrema()[0] == 255, (
                "apple-touch-icon must be fully opaque — iOS does not honour alpha"
            )


class TestWebManifest:
    def test_manifest_is_valid_json_with_theme_colour(self) -> None:
        manifest = json.loads((_STATIC / "site.webmanifest").read_text())
        assert manifest["theme_color"] == _THEME_COLOR
        assert manifest["background_color"] == _THEME_COLOR

    def test_manifest_declares_a_maskable_icon(self) -> None:
        manifest = json.loads((_STATIC / "site.webmanifest").read_text())
        purposes = [icon.get("purpose") for icon in manifest["icons"]]
        assert "maskable" in purposes, (
            "without a maskable icon Android crops the rounded tile badly"
        )


class TestHeadMarkup:
    """base.html is the only <head> in the app, so the markup has one home."""

    def test_head_links_the_ico(self) -> None:
        assert 'rel="icon"' in _BASE_TEMPLATE.read_text()
        assert "favicon.ico" in _BASE_TEMPLATE.read_text()

    def test_head_does_not_link_an_svg_icon(self) -> None:
        """An SVG rel=icon wins at EVERY size, defeating the hinted 16px frame.

        Browsers that honour `image/svg+xml` prefer it over the .ico even in the
        16px tab slot, so the greyed-out stem the hinting exists to prevent comes
        back on 1x displays. Deliberate decision, recorded in docs/brand-icon.md.
        """
        head = _BASE_TEMPLATE.read_text()
        assert 'type="image/svg+xml"' not in head, (
            "shipping an SVG rel=icon defeats the 16px hinting — .ico only"
        )

    def test_head_links_manifest_and_apple_touch_icon(self) -> None:
        head = _BASE_TEMPLATE.read_text()
        assert "site.webmanifest" in head
        assert "apple-touch-icon" in head


@pytest.fixture
def client(db_with_songs, tmp_path, monkeypatch):
    """A TestClient over a temp DB — mirrors the fixture in test_web.py."""
    inbox = tmp_path / "inbox"
    inbox.mkdir()
    monkeypatch.setenv("DB_PATH", str(db_with_songs))
    monkeypatch.setenv("INBOX_DIR", str(inbox))
    from importlib import reload

    import worship_catalog.web.app as app_module

    reload(app_module)
    return TestClient(app_module.app)


class TestFaviconRoute:
    """Browsers request /favicon.ico at the root, not under /static/."""

    def test_root_favicon_is_served(self, client) -> None:
        response = client.get("/favicon.ico")
        assert response.status_code == 200, (
            "the catch-all would otherwise answer /favicon.ico with a 404"
        )
        assert response.headers["content-type"] in (
            "image/vnd.microsoft.icon",
            "image/x-icon",
        )

    def test_root_favicon_answers_head(self, client) -> None:
        """Every GET route answers HEAD (#581)."""
        assert client.head("/favicon.ico").status_code == 200
